### TEST API

@LOCAL_API_ENDPOINT=http://localhost:8000
@AWS_API_ENDPOINT=https://abpa6z6ap46nb5sxdi4trcp3hi0scfza.lambda-url.eu-central-1.on.aws
@API_ENDPOINT={{AWS_API_ENDPOINT}}
@EXPERIMENT_ID=cc5fb48f-1ddc-4eb9-910f-975b9bb9e638

GET {{API_ENDPOINT}}/
Accept: application/json

### Health Check
GET {{API_ENDPOINT}}/health
Accept: application/json

### Get All Experiments
GET {{API_ENDPOINT}}/experiments
Accept: application/json

### Get Single Experiment
GET {{API_ENDPOINT}}/experiments/{{EXPERIMENT_ID}}
Accept: application/json

### Delete Single Experiment
DELETE {{API_ENDPOINT}}/experiments/{{EXPERIMENT_ID}}
Accept: application/json

### Create New Experiment
POST {{API_ENDPOINT}}/experiments
Content-Type: application/json

{
    "name": "furki experiment",
    "category": "rna-seq"
}


### Update Single Experiment | Status: 'Completed', 'Failed', 'Queued'
PATCH {{API_ENDPOINT}}/experiments/{{EXPERIMENT_ID}}
Content-Type: application/json

{
    "status": "Completed",
    "result": "test",
    "error": "No error."
}

### Semantic Search via AWS OpenSearch
POST {{API_ENDPOINT}}/search
Content-Type: application/json

{
    "query": "experiment",
    "top_k": 3
}
